### PR TITLE
Octave version 4.4.0

### PR DESCRIPTION
**Pull request by schoeps**

### CODE REVIEW

**Comment by dpo** [comment]
Again, we have
```
g++-5: internal compiler error: Killed (program cc1plus)
```
on Linux.

**Comment by dpo** [comment]
On Travis:
```
ftp://ftp.gnu.org/gnu/octave/octave-4.4.0.tar.lz
curl: (19) RETR response: 425
Error: Failed to download resource "octave"
Download failed: ftp://ftp.gnu.org/gnu/octave/octave-4.4.0.tar.lz
```
and
```
Error: 1 problem in 1 formula
dpo/openblas/octave:
  * stable and devel versions are identical
```

**Comment by stevestock** [comment]
@schoeps what do you currently recommend as the easiest way to install octave with the GUI?  Looks like there has been a lot of changes... there's the official formulas, you have a script from before the scientific->homebrew-core merge, and there's these alternate formulas.  I've seen your name come up a lot in searching around github on the subject.

**Comment by schoeps** [comment]
Yes, it's quite a mess since homebrew closed its science repository. To my best knowledge this formula here is the best option. I gives you octave 4.4 with some additional fixes. Do you need help installing it?

**Comment by stevestock** [comment]
I thought I knew what to do, but I tried:

```sh
brew install dpo/openblas/octave --with-qt --devel
```
and got:

```sh
==> ./bootstrap
==> ./configure --prefix=/usr/local/Cellar/octave/4.3-d0221e3675ef_1 --disable-s
==> make all
Last 15 lines from /Users/stevestock/Library/Logs/Homebrew/octave/03.make:
class QButtonGroup;
      ^
libgui/src/settings-dialog.cc:312:13: error: member access into incomplete type 'QButtonGroup'
  icon_group->addButton (ui->general_icon_letter);
            ^
/usr/local/Cellar/qt/5.11.0/include/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'QButtonGroup'
class QButtonGroup;
      ^
/bin/sh ./libtool  --tag=CXX   --mode=compile clang++ -std=gnu++11 -DHAVE_CONFIG_H -I.   -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtNetwork -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtOpenGL -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtPrintSupport -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtWidgets -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtGui -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtCore -I/usr/local/Cellar/qt/5.11.0/include -I./libgui/qterminal/libqterminal -Ilibgui/src -I./libgui/src -I./libgui/src/m-editor -I./libgui/src/qtinfo -I./libgui/graphics -I./liboctave/array -Iliboctave/numeric -I./liboctave/numeric -Iliboctave/operators -I./liboctave/operators -I./liboctave/system -I./liboctave/util -Ilibinterp -I./libinterp -Ilibinterp/parse-tree -I./libinterp/parse-tree -Ilibinterp/corefcn -I./libinterp/corefcn -I./libinterp/octave-value -I./liboctave/wrappers  -fPIC -D_THREAD_SAFE -pthread -Wall -W -Wshadow -Wold-style-cast -Wformat -Wpointer-arith -Wwrite-strings -Wcast-align -Wcast-qual -g -O2 -c -o libgui/src/libgui_src_la-variable-editor.lo `test -f 'libgui/src/variable-editor.cc' || echo './'`libgui/src/variable-editor.cc
8 errors generated.
make[2]: *** [libgui/src/libgui_src_la-settings-dialog.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtNetwork -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtOpenGL -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtPrintSupport -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtWidgets -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtGui -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtCore -I/usr/local/Cellar/qt/5.11.0/include -I./libgui/qterminal/libqterminal -Ilibgui/src -I./libgui/src -I./libgui/src/m-editor -I./libgui/src/qtinfo -I./libgui/graphics -I./liboctave/array -Iliboctave/numeric -I./liboctave/numeric -Iliboctave/operators -I./liboctave/operators -I./liboctave/system -I./liboctave/util -Ilibinterp -I./libinterp -Ilibinterp/parse-tree -I./libinterp/parse-tree -Ilibinterp/corefcn -I./libinterp/corefcn -I./libinterp/octave-value -I./liboctave/wrappers -fPIC -D_THREAD_SAFE -pthread -Wall -W -Wshadow -Wold-style-cast -Wformat -Wpointer-arith -Wwrite-strings -Wcast-align -Wcast-qual -g -O2 -c libgui/src/variable-editor.cc  -fno-common -DPIC -o libgui/src/.libs/libgui_src_la-variable-editor.o
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by schoeps** [comment]
Ok, yes. There is a new issue with qt 5.11 see #67. I will try to fix it.

**Comment by schoeps** [comment]
@stevestock please continue to discuss this issue within #67.

**Comment by dpo** [comment]
I don't understand why TravisCI constantly fails to download the octave source.

@schoeps Are you able to build the formula on Linux with Linuxbrew gcc? It keeps giving an internal compiler error on CicleCI. I'll re-run the build and try to ssh into the virtual machine to build gcc from source.

**Comment by schoeps** [comment]
@dpo we are not using brew on our linux cluster. However, I will gladly do some tests (it's time to get octave 4.4 out!). Which linux distribution do you recommend?

**Comment by dpo** [comment]
@schoeps I'm not much of a linux user myself. I was under the impression that you used Linuxbrew. I'm just trying to resolve the failed CircleCI build. I'm into the virtual machine now and building gcc from source to see if it resolves the issue.

**Comment by dpo** [comment]
Oh well, there are tons of obstacles to building this on Linux... Currently waiting for https://github.com/Linuxbrew/homebrew-xorg/pull/351 to be merged.

**Comment by apjanke** [comment]
Hi folks. I tried out this PR locally, and one of the tests is failing.

Is this expected, or something to be worried about?

```
$ brew install -s dpo/openblas/octave                                                                    schoeps-master
...
==> make all
==> make check 2>&1 | tee "test/make-check.log"
Warning: Some tests failed. Details are given in /usr/local/opt/octave/make-check.log.
...
```

In `/usr/local/opt/octave/make-check.log`:

```

  miscellaneous/tar.m .........................................a dir2
a dir2/file2
a file1
 PASS      5/6   
                                                                  FAIL    1
```

```
>>>>> processing /private/tmp/octave-20180617-51586-16z5pn2/octave-4.4.0/scripts/miscellaneous/tar.m
***** test
 ## test tar together with untar
 orig_dir = pwd ();
 unwind_protect
   dirname = tarname = outdir = "";
   dirname = tempname ();
   assert (mkdir (dirname));
   chdir (dirname);
   dirname2 = "dir2";
   assert (mkdir (dirname2));
   fname1 = "file1";
   fname2 = fullfile (dirname2, "file2");
   fid = fopen (fname1, "wt");
   assert (fid >= 0);
   fdisp (fid, "Hello World");
   fclose (fid);
   fid = fopen (fname2, "wt");
   assert (fid >= 0);
   fdisp (fid, "Goodbye World");
   fclose (fid);
   tarname = [tempname() ".tar"];
   filelist = tar (tarname, {dirname2, fname1});
   if (! strcmp (filelist{3}, fname1))
     error ("tar file contents does not match expected file");
   endif
   if (! exist (tarname, "file"))
     error ("tar archive file cannot be found!");
   endif
   outdir = tempname;
   untar (tarname, outdir);
   fid = fopen (fullfile (outdir, fname1), "rt");
   assert (fid >= 0);
   str = fgetl (fid);
   fclose (fid);
   assert (str, "Hello World");
   fid = fopen (fullfile (outdir, fname2), "rt");
   assert (fid >= 0);
   str = fgetl (fid);
   fclose (fid);
   assert (str, "Goodbye World");
 unwind_protect_cleanup
   chdir (orig_dir);
   unlink (tarname);
   confirm_recursive_rmdir (false, "local");
   if (exist (dirname))
     rmdir (dirname, "s");
   endif
   if (exist (outdir))
     rmdir (outdir, "s");
   endif
 end_unwind_protect
!!!!! test failed
filelist(3): out of bound 0
```

**Comment by apjanke** [comment]
BTW, aside from that failed test, I can report a successful build on my macOS 10.13.5 box. Build succeeds, and the GUI runs.

Thanks for putting this together!

**Comment by schoeps** [comment]
@apjanke This is nothing to worry about. It is an issue of bsdtar vs. gnutar. I know how how to fix it (there os also a bug report about it). I am just lacking time.

Regarding your ideas: I would enjoy if this formula (the gui stuff, without openblas) gets merged to core but I will not do it. 

I think it's agreat idea to create a website for "octave app". I am currently on a business trip. Let's do it in one wek from now. What do you think?

**Comment by apjanke** [comment]
Sure. How about we do it through GitHub pages - I'll make an "octave-app" organization, add you to the org, and we can host it as an organization Page?

(I think the GUI stuff can probably make it back to the core formula, as long as the crashiness is fixed and there aren't too many patches that need to be pulled in.)

**Comment by apjanke** [comment]
P.S. @schoeps - want to shoot me your email so we can talk outside of GitHub? I'm andrew@apjanke.net.

**Pull request closed without merging**
