### PR TITLE
metis4, scotch5, sundials27: rename using new <name>@X.Y convention

### PR DESCRIPTION
**Pull request by apjanke**
The new <formula>@X.Y naming convention for versioned formulae is well established in core Homebrew. How about using it here, too?

This PR includes a `formula_renames.json` to provide continuity for users who might already have these installed.

### CODE REVIEW

**Comment by dpo** [comment]
Thanks! Any idea what this is about:
```
An error occurred while NewFormulaAudit/DependencyOrder cop was inspecting /usr/local/Homebrew/Library/Taps/dpo/homebrew-openblas/sundials@2.7.rb:1:0.
To see the complete backtrace run rubocop -d.

1 error occurred:
An error occurred while NewFormulaAudit/DependencyOrder cop was inspecting /usr/local/Homebrew/Library/Taps/dpo/homebrew-openblas/sundials@2.7.rb:1:0.
undefined method `metadata' for nil:NilClass
```

**Comment by apjanke** [comment]
That looks like a bug in `brew audit` itself, not in your formula. You "should never" get error messages like that. ;) I'll look in to it.

**Comment by dpo** [comment]
@apjanke Any news here?

**Comment by apjanke** [comment]
I believe this is fixed in `brew audit` and/or its dependency gems; I am now getting normal audit error messages locally:

```
$ brew audit --strict sundials@2.7
dpo/openblas/sundials@2.7:
  * C: 17: col 3: Versioned formulae should not use `conflicts_with`. Use `keg_only :versioned_formula` instead.
  * sundials@2.7 is versioned but no sundials formula exists
Error: 2 problems in 1 formula
```

I think its `keg_only` advice is a good idea. I'll update the formula to do so, if you're okay with that. (I think it would make it easier on your users to be able to install sundials@2.7 at the same time as plain sundials.)

This one: "sundials@2.7 is versioned but no sundials formula exists" appears to be an error; there's clearly a sundials formula. Maybe the audit is not looking in the core tap when auditing a formula from a custom tap. I'll look in to that, but I think you can just ignore it for now. (Or for that matter, you might want to add your own OpenBLAS-enabled `sundials` formula in preparation for when Octave support catches up with SUNDIALS 3.x.)

**Comment by dpo** [comment]
> I think its keg_only advice is a good idea. I'll update the formula to do so, if you're okay with that. (I think it would make it easier on your users to be able to install sundials@2.7 at the same time as plain sundials.)

Would ba great indeed! Thanks @apjanke !

**Comment by apjanke** [comment]
I've made sundials@2.7 keg_only in another commit on this PR. 

I think you can ignore the remaining "sundials@2.7 is versioned but no sundials formula exists" brew audit warning.

**Comment by dpo** [comment]
Would you please rebase this PR?

**Comment by apjanke** [comment]
Rebased on master.

I think this PR is still relevant, for its original stated reasons. Still no functional changes: it's just to align naming conventions with upstream's.

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
