### PR TITLE
Move formulae to a Formula subdir

### PR DESCRIPTION
**Pull request by apjanke**
What do you think about moving the formulae to a Formula subdirectory, using Homebrew's newer tap directory structure? This would keep the root directory cleaner, for use with the `README.md`, `ci` dir, and `formula_renames.json` etc if you wanted to add them.

### CODE REVIEW

**Comment by dpo** [comment]
Good idea, but please commit the Formula subdir then ;-).

**Comment by apjanke** [comment]
Oh my *gosh*, I feel like a knucklehead. Nice trick to pull on my first set of PRs for a project.

Fixed!

**Comment by apjanke** [comment]
Looks like this move breaks some of the CI setup. I'll look in to fixing that as part of this PR.

From the Travis output:

```
0.02s$ ln -s "$TRAVIS_BUILD_DIR" $(brew --repo)/Library/Taps/dpo/homebrew-openblas
install.11
0.01s$ export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/dpo/homebrew-openblas"
0.01s$ chmod 0644 $(brew --repo)/Library/Taps/dpo/homebrew-openblas/*.rb
chmod: cannot access ‘/home/linuxbrew/.linuxbrew/Library/Taps/dpo/homebrew-openblas/*.rb’: No such file or directory
The command "chmod 0644 $(brew --repo)/Library/Taps/dpo/homebrew-openblas/*.rb" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by apjanke** [comment]
Some of the formulae builds are failing in this PR:
* metis
* hwloc@1.11

Metis failure:

```
-- Check for working C compiler: /home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-5 -- broken
CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.11.4/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler
    "/home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-5"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: /tmp/metis-20180715-12129-1hstv53/metis-5.1.0/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_472f0/fast"
    /usr/bin/make -f CMakeFiles/cmTC_472f0.dir/build.make CMakeFiles/cmTC_472f0.dir/build
    make[1]: Entering directory `/tmp/metis-20180715-12129-1hstv53/metis-5.1.0/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_472f0.dir/testCCompiler.c.o
    /home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-5    -o CMakeFiles/cmTC_472f0.dir/testCCompiler.c.o   -c /tmp/metis-20180715-12129-1hstv53/metis-5.1.0/build/CMakeFiles/CMakeTmp/testCCompiler.c
    /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/cc1: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
    make[1]: *** [CMakeFiles/cmTC_472f0.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory `/tmp/metis-20180715-12129-1hstv53/metis-5.1.0/build/CMakeFiles/CMakeTmp'
    make: *** [cmTC_472f0/fast] Error 2
    
  
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)
```

hwloc failure:

```
configure: error: in `/tmp/hwloc@1.11-20180715-23106-jsdqcv/hwloc-1.11.9':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Also audit failures:

```
==> brew audit dpo/openblas/hwloc@1.11 --online --new-formula
Error: 3 problems in 1 formula
dpo/openblas/hwloc@1.11:
  * hwloc@1.11 is versioned but no hwloc formula exists
  * Formulae should not have an unstable spec
  * 'revision 1' should be removed
==> FAILED
==> brew audit dpo/openblas/scalapack --online --new-formula
Error: 1 problem in 1 formula
dpo/openblas/scalapack:
  * The URL http://www.netlib.org/scalapack/ should use HTTPS rather than HTTP
==> FAILED
==> brew audit dpo/openblas/arpack --online --new-formula
Error: 1 problem in 1 formula
dpo/openblas/arpack:
  * Formulae should not have an unstable spec
==> FAILED
brew audit dpo/openblas/starpu --online --new-formula[0m
Error: 1 problem in 1 formula
dpo/openblas/starpu:
  * Formulae should not have an unstable spec
==> FAILED
```

I don't think these are regressions from this PR, so I'll address them in a separate PR.

I think these "unstable spec" audits are not relevant to your case, and can just be ignored. Better yet, it would be nice to disable them. Homebrew core audits are getting aggressive, and they're not all necessarily needed for custom taps.

Maybe you could just remove the `--new-formula` option from the audit call?

**Comment by apjanke** [comment]
I've submitted a PR to brew to relax a couple of these audits that I think are only relevant to the official core tap: https://github.com/Homebrew/brew/pull/4496.

**Comment by dpo** [comment]
@apjanke Would you mind rebasing this now? Thanks!

**Comment by apjanke** [comment]
Rebased!

**Comment by dpo** [comment]
Merged manually due to another conflict. Many thanks!

**Pull request closed without merging**
