### PR TITLE
Octave to 4.2.2

### PR DESCRIPTION
**Pull request by schoeps**
New version 4.2.2 and fixed issue https://github.com/dpo/homebrew-openblas/issues/53.

### CODE REVIEW

**Comment by schoeps** [comment]
@dpo did you give up on this repository?

**Comment by dpo** [comment]
Did not give up at all. Time is just short.

**Comment by dpo** [comment]
@schoeps Could you rebase this branch? There are errors due to old `=> :run` dependencies that have since been fixed. Thanks!

**Comment by schoeps** [comment]
Sorry, I messed up and pushed in the main repo :( Suggestions?

**Comment by dpo** [comment]
I forced push to master to undo that last commit. Hopefully, that was fast enough that noone will run into problems.

**Comment by schoeps** [comment]
Thanks. I tried to handle two merge request for the old stable (octave 4.2) and the new release (4.4) at the same time. I obviously got lost :( 

So, shall we go for 4.4 (online since yesterday) or bugfixing the old 4.2?

**Comment by dpo** [comment]
Let's go with 4.4 if we can get it to build. I'm not sure about the errors in #60.

**Comment by schoeps** [comment]
Ok, I will start with a new request from scratch.

**Comment by schoeps** [comment]
Ok, something is wrong with my local configuration. Sorry, I pushed again to the main repo :( Maybe, it's better to remove my write access. This is annoying.

(I switched recently to a graphical GIT client: Tower. Maybe that was not a good idea)

**Comment by dpo** [comment]
I thought I could tweak your permissions, but apparently, it's all or nothing. Maybe there's something wrong with your remotes?! I personally don't use graphical git clients. Having to write everything out on the command line can be tedious, but at least, you know you're running the right command.

**Comment by schoeps** [comment]
> but at least, you know you're running the right command.

I cannot argue here :)  

However, I have opened #61. Let's see how it goes.

**Pull request closed without merging**
